### ISSUE TITLE
Не компилируется

### ISSUE THREAD

**Issue by finomen** [Romanosov/Cpp#1]
Scanning dependencies of target HW1
[100%] Building CXX object CMakeFiles/HW1.dir/main.cpp.o
/home/finomen/cpp_2014/50/SimpleCalc/main.cpp: In function ‘long long int calcul
ate(std::string)’:
/home/finomen/cpp_2014/50/SimpleCalc/main.cpp:69:33: error: ‘itoa’ was not decla
red in this scope
make[2]: *** [CMakeFiles/HW1.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/HW1.dir/all] Error 2
make: *** [all] Error 2

**Comment by Romanosov** [comment]
Исправлено. Проверьте, пожалуйста.

**Comment by Romanosov** [comment]
Исправлено.


Понедельник,  9 марта 2015, 2:45 -07:00 от Nikolay Filchenko <notifications@github.com>:
